### ISSUE TITLE
Don't use aboslute paths

### ISSUE THREAD

**Issue by leo-rp** [julianleon17/app-store-frontend#1]
https://github.com/julianleon17/app-store-frontend/blob/6718e366f39cbeef58c600b176cf77f7d12d18a9/src/views/Account.svelte#L3

Please try to sue something like @ instead of ../../

https://dev.to/sjafferi/absolute-paths-in-svelte-488c

**Comment by julianleon17** [comment]
The issue was solved, thank you for your feedback!
